export const SET_ARRAY="SET_ARRAY";
export const ERROR_STATUS="ERROR_STATUS";
export const LOADING_STATUS="LOADING_STATUS";
export const DATA_STATUS="DATA_STATUS";
export const BUTTON_TOGGLE="BUTTON_TOGGLE";
export const TOGGLE_SCROLL="TOGGLE_SCROLL";
export const COMPAREONE_STATUS="COMPAREONE_STATUS";
export const COMPARETWO_STATUS="COMPARETWO_STATUS";
